# Generated by Django 5.2.2 on 2025-06-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='descripition',
            new_name='description',
        ),
    ]
