# Generated by Django 5.2.2 on 2025-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_descripition_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(default='https://static.vecteezy.com/system/resources/previews/010/279/249/non_2x/carton-box-color-icon-illustration-vector.jpg'),
        ),
    ]
